stages:
  - build
  - test

build_job:
  stage: build
  script:
    - echo "Building the project..."
    - npm install
    - npm run build

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - npm test
